variables:
  tenant_id: '72f988bf-86f1-41af-91ab-2d7cd011db47'
  subscription_id: ''
  application_id: ''
  datasets_storage_account: 'innereyepublicdatasets'
  datasets_container: 'datasets'
  azureml_datastore: 'innereyedatasets'
  resource_group: 'InnerEye-DeepLearning'
  docker_shm_size: '440g'
  workspace_name: 'InnerEye-DeepLearning'
  cluster: 'training-nd24'
  model_configs_namespace: ''
  extra_code_directory: ''
