dataset:
  name: RSNAKaggle
  dataset_dir: /datadrive/rsna_train
train:
  seed: 3
  batch_size: 1600
  base_lr: 1e-3
  output_dir: kaggle/ssup
  resume_from_last_checkpoint: False
  self_supervision:
    type: simclr
    encoder_name: resnet50
    use_balanced_binary_loss_for_linear_head: True
scheduler:
  epochs: 1500
preprocess:
  center_crop_size: 224
  resize: 256
augmentation:
  use_random_horizontal_flip: True
  use_random_affine: True
  use_random_color: True
  use_random_crop: True
  use_gamma_transform: True
  use_random_erasing: True
  add_gaussian_noise: True
  use_elastic_transform: True
  random_horizontal_flip:
    prob: 0.5
  random_erasing:
      scale: (0.005, 0.08)
      ratio: (0.33, 3)
  random_affine:
    max_angle: 180
    max_horizontal_shift: 0.00
    max_vertical_shift: 0.00
    max_shear: 40
  elastic_transform:
    sigma: 4
    alpha: 34
    p_apply: 0.4
  random_color:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.0
  random_crop:
    scale: (0.6, 1.0)
