steps:
  - checkout: self
    lfs: true

  - bash: |
      if [ $(Agent.OS) = 'Windows_NT' ]
      then subdir=Scripts
      else subdir=bin
      fi
      echo "Adding this directory to PATH: $CONDA/$subdir"
      echo "##vso[task.prependpath]$CONDA/$subdir"
    displayName: Add conda to PATH
    condition: succeeded()

  - bash: |
      conda install conda=4.8.3 -y
      conda --version
      conda list
    displayName: Print conda version and package list

  # Linux only; not needed for Windows
  - bash: |
      sudo chown -R $USER /usr/share/miniconda
    condition: and(succeeded(), eq( variables['Agent.OS'], 'Linux' ))
    displayName: Take ownership of conda installation

  - bash: |
      sed -i -e "s/subscription_id: ''/subscription_id: '$(InnerEyeDevSubscriptionID)'/" InnerEye/settings.yml
      sed -i -e "s/application_id: ''/application_id: '$(InnerEyeDeepLearningServicePrincipalID)'/" InnerEye/settings.yml
    displayName: Provide subscription information
