name: train-$(Date:yyyyMMdd)$(Rev:-r)
jobs:
  - job: Train
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: train_template.yml
        parameters:
          wait_for_completion: 'False'
